-- V32__add_fiscal_profile_cfop_column.sql
-- Fiscal domain (FARELO-153, "Adicionar CFOP", prompt mestre seção 24:
-- "Perfis fiscais devem permitir futuramente: NCM, CFOP, CST/CSOSN, CEST,
-- origem, cBenef, ICMS, CBS, IBS"). Adds the CFOP column that fiscal_profile
-- (V27) deliberately left out until a concrete ticket needed it — see that
-- migration's own comment ("Deliberately no NCM/CFOP/CST/CSOSN ... column
-- yet ... FARELO-152/153/154"). Second of the three fiscal codes named as
-- their own tickets, mirroring V30 (NCM, FARELO-152) almost exactly.
--
-- CFOP (Código Fiscal de Operações e Prestações) is a real, standardized
-- Brazilian tax code classifying the nature of a fiscal operation (e.g.
-- sale within-state vs. out-of-state), always exactly 4 numeric digits
-- (never letters, never a different length) — this is fixed by Brazilian
-- tax law/nomenclature, not an app-specific choice.
--
-- Nullable, no default: same reasoning as fiscal_profile.ncm (V30) —
-- existing fiscal_profile rows predate this ticket and have no CFOP, and
-- there is no meaningful "default CFOP" a migration could backfill (unlike
-- active/createdAt, whose defaults are genuinely universal). NULL means "no
-- CFOP configured for this fiscal profile yet", a distinct, permanent
-- state an Admin will fill in later — not a temporary placeholder forced by
-- the migration.
--
-- VARCHAR(4): exact max length of a real CFOP code (always 4 digits).
--
-- CHECK (cfop IS NULL OR cfop ~ '^[0-9]{4}$'): mirrors the
-- fiscal_profile.ncm (V30) precedent exactly — format validation already
-- lives at the request layer (@Pattern on FiscalProfileRequest/
-- FiscalProfileUpdateRequest, see those classes) for traffic that goes
-- through the DTO boundary, but this column has no equivalent guard for a
-- write path that bypasses the DTO (e.g. a direct repository save, a future
-- data migration/import), so the same "validation at the DTO boundary + DB
-- CHECK as a defense-in-depth backstop" pattern applies here too. A regex
-- CHECK rather than the VARCHAR + IN (...) convention used for this
-- schema's enum-backed columns (e.g. ingredient.unit, V16) — CFOP isn't a
-- small fixed enumeration, it's a large, externally-maintained government
-- table of hundreds of valid codes that changes over time, so the DB only
-- enforces the one property that's actually structural and permanent
-- (exactly 4 digits), not membership in the current CFOP table (which
-- belongs to a future integration/lookup concern, not this ticket).

ALTER TABLE fiscal_profile
    ADD COLUMN cfop VARCHAR(4)
        CHECK (cfop IS NULL OR cfop ~ '^[0-9]{4}$');
